from __future__ import annotations

from typing import TypedDict


class BuiltinAiJob(TypedDict):
    skill_name: str
    skill_category: str
    description: str
    revision_title: str
    revision_content: str
    change_note: str
    job_name: str
    schedule_label: str
    schedule_rrule_or_cron: str
    job_type: str
    display_group: str
    result_schema_version: str
    engine_type: str


BUILTIN_AI_JOBS: list[BuiltinAiJob] = [
    {
        "skill_name": "盘前消息面挖掘",
        "skill_category": "news-scan",
        "description": "盘前汇总消息面、板块催化与风险提示",
        "revision_title": "盘前消息面挖掘 v1",
        "revision_content": "输出 headline_items、market_implications、watch_themes。",
        "change_note": "bootstrap builtin registry",
        "job_name": "08:20 盘前消息面挖掘",
        "schedule_label": "08:20",
        "schedule_rrule_or_cron": "20 8 * * 0-4",
        "job_type": "news_scan",
        "display_group": "盘前",
        "result_schema_version": "2.0",
        "engine_type": "claude-code",
    },
    {
        "skill_name": "集合竞价分析",
        "skill_category": "stock-pick",
        "description": "盘前竞价强弱、资金面与情绪确认",
        "revision_title": "集合竞价分析 v1",
        "revision_content": "输出结构化竞价选股卡。",
        "change_note": "bootstrap builtin registry",
        "job_name": "09:26 集合竞价分析",
        "schedule_label": "09:26",
        "schedule_rrule_or_cron": "26 9 * * 0-4",
        "job_type": "stock_pick",
        "display_group": "盘中",
        "result_schema_version": "2.0",
        "engine_type": "claude-code",
    },
    {
        "skill_name": "弱转强候选筛选",
        "skill_category": "stock-pick",
        "description": "从弱转强模型中筛出候选股票",
        "revision_title": "弱转强候选筛选 v1",
        "revision_content": "输出 candidate 级别结构化选股卡。",
        "change_note": "bootstrap builtin registry",
        "job_name": "09:40 弱转强-候选筛选",
        "schedule_label": "09:40",
        "schedule_rrule_or_cron": "40 9 * * 0-4",
        "job_type": "stock_pick",
        "display_group": "盘中",
        "result_schema_version": "2.0",
        "engine_type": "claude-code",
    },
    {
        "skill_name": "弱转强转强确认",
        "skill_category": "stock-confirm",
        "description": "确认候选股是否出现转强信号",
        "revision_title": "弱转强转强确认 v1",
        "revision_content": "输出 confirm 级别结构化选股卡。",
        "change_note": "bootstrap builtin registry",
        "job_name": "10:05 弱转强-转强确认",
        "schedule_label": "10:05",
        "schedule_rrule_or_cron": "5 10 * * 0-4",
        "job_type": "stock_confirm",
        "display_group": "盘中",
        "result_schema_version": "2.0",
        "engine_type": "claude-code",
    },
    {
        "skill_name": "早盘复盘",
        "skill_category": "review",
        "description": "半日大盘、情绪和推荐股反馈",
        "revision_title": "早盘复盘 v1",
        "revision_content": "输出半日 market_summary 与 recommended_picks_review。",
        "change_note": "bootstrap builtin registry",
        "job_name": "12:00 早盘复盘",
        "schedule_label": "12:00",
        "schedule_rrule_or_cron": "0 12 * * 0-4",
        "job_type": "day_review",
        "display_group": "盘后",
        "result_schema_version": "2.0",
        "engine_type": "claude-code",
    },
    {
        "skill_name": "尾盘选股",
        "skill_category": "stock-pick",
        "description": "尾盘承接与次日预期选股",
        "revision_title": "尾盘选股 v1",
        "revision_content": "输出尾盘承接结构化选股卡。",
        "change_note": "bootstrap builtin registry",
        "job_name": "14:50 尾盘选股",
        "schedule_label": "14:50",
        "schedule_rrule_or_cron": "50 14 * * 0-4",
        "job_type": "stock_pick",
        "display_group": "盘后",
        "result_schema_version": "2.0",
        "engine_type": "claude-code",
    },
    {
        "skill_name": "超短线复盘",
        "skill_category": "review",
        "description": "盘后超短线大盘、主线与失败模式总结",
        "revision_title": "超短线复盘 v1",
        "revision_content": "输出完整交易日复盘包。",
        "change_note": "bootstrap builtin registry",
        "job_name": "19:00 超短线复盘",
        "schedule_label": "19:00",
        "schedule_rrule_or_cron": "0 19 * * 0-4",
        "job_type": "day_review",
        "display_group": "盘后",
        "result_schema_version": "2.0",
        "engine_type": "claude-code",
    },
    {
        "skill_name": "超短线盘后选股",
        "skill_category": "stock-pick",
        "description": "盘后超短线候选池输出",
        "revision_title": "超短线盘后选股 v3",
        "revision_content": "输出盘后候选结构化选股卡。",
        "change_note": "bootstrap builtin registry",
        "job_name": "20:00 超短线盘后选股(v3)",
        "schedule_label": "20:00",
        "schedule_rrule_or_cron": "0 20 * * 0-4",
        "job_type": "stock_pick",
        "display_group": "夜间",
        "result_schema_version": "2.0",
        "engine_type": "claude-code",
    },
    {
        "skill_name": "大象起舞选股",
        "skill_category": "stock-pick",
        "description": "大市值异动与机构风格候选",
        "revision_title": "大象起舞选股 v1",
        "revision_content": "输出大票异动结构化选股卡。",
        "change_note": "bootstrap builtin registry",
        "job_name": "20:05 大象起舞选股",
        "schedule_label": "20:05",
        "schedule_rrule_or_cron": "5 20 * * 0-4",
        "job_type": "stock_pick",
        "display_group": "夜间",
        "result_schema_version": "2.0",
        "engine_type": "claude-code",
    },
    {
        "skill_name": "ST股挖掘",
        "skill_category": "stock-pick",
        "description": "ST 方向主题催化与风格观察",
        "revision_title": "ST股挖掘 v1",
        "revision_content": "输出 ST 方向结构化选股卡。",
        "change_note": "bootstrap builtin registry",
        "job_name": "20:30 ST股挖掘",
        "schedule_label": "20:30",
        "schedule_rrule_or_cron": "30 20 * * 0-4",
        "job_type": "stock_pick",
        "display_group": "夜间",
        "result_schema_version": "2.0",
        "engine_type": "claude-code",
    },
    {
        "skill_name": "每日持仓复盘",
        "skill_category": "review",
        "description": "复盘持仓表现与操作得失",
        "revision_title": "每日持仓复盘 v1",
        "revision_content": "输出 position_review 与 lesson_items。",
        "change_note": "bootstrap builtin registry",
        "job_name": "21:30 每日持仓复盘",
        "schedule_label": "21:30",
        "schedule_rrule_or_cron": "30 21 * * 0-4",
        "job_type": "position_review",
        "display_group": "夜间",
        "result_schema_version": "2.0",
        "engine_type": "claude-code",
    },
    {
        "skill_name": "超短线周度经验汇总",
        "skill_category": "review",
        "description": "沉淀一周内经验与失败模式",
        "revision_title": "超短线周度经验汇总 v1",
        "revision_content": "输出 weekly_review 与 lesson_items。",
        "change_note": "bootstrap builtin registry",
        "job_name": "周五22:00 超短线周度经验汇总",
        "schedule_label": "周五22:00",
        "schedule_rrule_or_cron": "0 22 * * 4",
        "job_type": "weekly_review",
        "display_group": "周报",
        "result_schema_version": "2.0",
        "engine_type": "claude-code",
    },
]
